/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CVSAdminRole;

import Business.Store;
import Business.StoreCatalog;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ayushi
 */
public class ManageStoreCatalog extends javax.swing.JPanel {

    /**
     * Creates new form ManageStoreCatalog
     */
    private JPanel userProcessContainer;
    private StoreCatalog storeCatalog;
    
    public ManageStoreCatalog(JPanel userProcessContainer, StoreCatalog storeCatalog ) {
        
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.storeCatalog= storeCatalog;
        populateTable();
    }

    public void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) storeJTable.getModel();
        model.setRowCount(0);
        for (Store s : storeCatalog.getStoreList()) {
            Object row[] = new Object[3];
            row[0] = s;
            row[1] = s.getStoreId();
            row[2] = s.getAddress();
            model.addRow(row);
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteStoreJButton = new javax.swing.JButton();
        storeSearchJButton = new javax.swing.JButton();
        backMSJButton = new javax.swing.JButton();
        searchStoreJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        storeJTable = new javax.swing.JTable();
        storeViewJButton = new javax.swing.JButton();

        deleteStoreJButton.setFont(new java.awt.Font("Calibri", 3, 15)); // NOI18N
        deleteStoreJButton.setForeground(new java.awt.Color(153, 0, 0));
        deleteStoreJButton.setText("Delete Store >>");
        deleteStoreJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteStoreJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStoreJButtonActionPerformed(evt);
            }
        });

        storeSearchJButton.setFont(new java.awt.Font("Calibri", 3, 15)); // NOI18N
        storeSearchJButton.setForeground(new java.awt.Color(153, 0, 0));
        storeSearchJButton.setText("Search >>");
        storeSearchJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        storeSearchJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeSearchJButtonActionPerformed(evt);
            }
        });

        backMSJButton.setFont(new java.awt.Font("Calibri", 3, 15)); // NOI18N
        backMSJButton.setForeground(new java.awt.Color(153, 0, 0));
        backMSJButton.setText("<<Back");
        backMSJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backMSJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMSJButtonActionPerformed(evt);
            }
        });

        searchStoreJTextField.setBackground(new java.awt.Color(240, 240, 240));
        searchStoreJTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("Manage Store Catalog");

        storeJTable.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        storeJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Store Name", "Store Id", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(storeJTable);

        storeViewJButton.setFont(new java.awt.Font("Calibri", 3, 15)); // NOI18N
        storeViewJButton.setForeground(new java.awt.Color(153, 0, 0));
        storeViewJButton.setText("View Store Details >>");
        storeViewJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        storeViewJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeViewJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchStoreJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(storeSearchJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(storeViewJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(deleteStoreJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(backMSJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(storeViewJButton)
                            .addComponent(deleteStoreJButton))
                        .addGap(34, 34, 34)
                        .addComponent(storeSearchJButton))
                    .addComponent(searchStoreJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(backMSJButton)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void storeViewJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeViewJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = storeJTable.getSelectedRow();
        
        if(selectedRow>=0){
            Store st = (Store)storeJTable.getValueAt(selectedRow,0);
            ViewStore vs = new ViewStore(userProcessContainer,st);
            userProcessContainer.add("ViewStore", vs);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            
    }                                                

        else{
             JOptionPane.showMessageDialog(null,"Please Select a row from the table first","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_storeViewJButtonActionPerformed

    private void deleteStoreJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStoreJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = storeJTable.getSelectedRowCount();
        if(selectedRow>0){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null,"WOULD YOU LIKE TO DELETE THE STORE?","Warning", dialogButton);
            if(dialogResult==JOptionPane.YES_OPTION){
                Store ss = (Store)storeJTable.getValueAt(selectedRow,0);
                storeCatalog.removeStore(ss);
                populateTable();
                
            }
        
        }else{
            
            JOptionPane.showMessageDialog(null,"Please Select a row from the table first","WARNING", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_deleteStoreJButtonActionPerformed

    private void backMSJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMSJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backMSJButtonActionPerformed

    private void storeSearchJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeSearchJButtonActionPerformed
        // TODO add your handling code here:
        String id = searchStoreJTextField.getText();
        Store store = storeCatalog.searchStore(id);
        if(store==null){
            JOptionPane.showMessageDialog(null,"Please enter a proper Name");
            return;
        }
            ViewStore vs = new ViewStore(userProcessContainer,store);
            userProcessContainer.add("ViewStore", vs);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        
    }//GEN-LAST:event_storeSearchJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backMSJButton;
    private javax.swing.JButton deleteStoreJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchStoreJTextField;
    private javax.swing.JTable storeJTable;
    private javax.swing.JButton storeSearchJButton;
    private javax.swing.JButton storeViewJButton;
    // End of variables declaration//GEN-END:variables

    
}
