/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CVSAdminRole;

import Business.Store;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ayushi
 */
public class ViewStore extends javax.swing.JPanel {

    /**
     * Creates new form ViewStore
     */
    private JPanel userProcessContainer;
    private Store store;

    public ViewStore(JPanel userProcessContainer, Store store) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.store = store;
        populateForm();
        saveVSJButton.setEnabled(false);
    }

    public void populateForm() {
        storeNameJTextField.setText(store.getStoreName());
        storeIdJTextField.setText(store.getStoreName());
        addressJTextField.setText(store.getAddress());
        contactJTextField.setText(store.getContact());
        emailJTextField.setText(store.getEmail());
        managerJTextField.setText(store.getManager());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        storeNameJTextField = new javax.swing.JTextField();
        storeIdJTextField = new javax.swing.JTextField();
        addressJTextField = new javax.swing.JTextField();
        contactJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        emailJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        managerJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        backVSJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        saveVSJButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        updateVSJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel6.setText("Email");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel7.setText("Manager");

        storeNameJTextField.setBackground(java.awt.SystemColor.controlHighlight);

        storeIdJTextField.setBackground(java.awt.SystemColor.controlHighlight);

        addressJTextField.setBackground(java.awt.SystemColor.controlHighlight);

        contactJTextField.setBackground(java.awt.SystemColor.controlHighlight);
        contactJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactJTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("  View Store");

        emailJTextField.setBackground(java.awt.SystemColor.controlHighlight);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel2.setText("Store Name");

        managerJTextField.setBackground(java.awt.SystemColor.controlHighlight);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel3.setText("Store Id");

        backVSJButton.setFont(new java.awt.Font("Calibri", 3, 15)); // NOI18N
        backVSJButton.setForeground(new java.awt.Color(153, 0, 0));
        backVSJButton.setText("<< Back");
        backVSJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backVSJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backVSJButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel4.setText("Address");

        saveVSJButton.setFont(new java.awt.Font("Calibri", 3, 15)); // NOI18N
        saveVSJButton.setForeground(new java.awt.Color(153, 0, 0));
        saveVSJButton.setText("Save");
        saveVSJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveVSJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveVSJButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel5.setText("Contact No.");

        updateVSJButton.setFont(new java.awt.Font("Calibri", 3, 15)); // NOI18N
        updateVSJButton.setForeground(new java.awt.Color(153, 0, 0));
        updateVSJButton.setText("Update");
        updateVSJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateVSJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateVSJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(storeIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(storeNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addressJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(contactJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(managerJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveVSJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(updateVSJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(backVSJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(222, 222, 222))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(storeNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(storeIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addressJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(contactJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(emailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(managerJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveVSJButton)
                    .addComponent(updateVSJButton))
                .addGap(33, 33, 33)
                .addComponent(backVSJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void contactJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactJTextFieldActionPerformed

    private void updateVSJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateVSJButtonActionPerformed
        // TODO add your handling code here:
        storeNameJTextField.setEnabled(true);
        storeIdJTextField.setEnabled(true);
        addressJTextField.setEnabled(true);
        contactJTextField.setEnabled(true);
        emailJTextField.setEnabled(true);
        managerJTextField.setEnabled(true);
        saveVSJButton.setEnabled(true);
        updateVSJButton.setEnabled(false);
    }//GEN-LAST:event_updateVSJButtonActionPerformed

    private void saveVSJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveVSJButtonActionPerformed
        // TODO add your handling code here:
        try {

            store.setStoreName(storeNameJTextField.getText());
            store.setStoreId(storeIdJTextField.getText());
            store.setAddress(addressJTextField.getText());
            store.setContact(contactJTextField.getText());
            store.setEmail(emailJTextField.getText());
            store.setManager(managerJTextField.getText());
            JOptionPane.showMessageDialog(null, "Store details updated Successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
            saveVSJButton.setEnabled(false);
            updateVSJButton.setEnabled(true);
            storeNameJTextField.setEnabled(false);
            storeIdJTextField.setEnabled(false);
            addressJTextField.setEnabled(false);
            contactJTextField.setEnabled(false);
            emailJTextField.setEnabled(false);
            managerJTextField.setEnabled(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter proper details", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_saveVSJButtonActionPerformed

    private void backVSJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backVSJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length -1];
        ManageStoreCatalog mcs = (ManageStoreCatalog) component;
        mcs.populateTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backVSJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JButton backVSJButton;
    private javax.swing.JTextField contactJTextField;
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField managerJTextField;
    private javax.swing.JButton saveVSJButton;
    private javax.swing.JTextField storeIdJTextField;
    private javax.swing.JTextField storeNameJTextField;
    private javax.swing.JButton updateVSJButton;
    // End of variables declaration//GEN-END:variables
}
