/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.StoreAdminRole;

import Business.Store;
import Business.SupplierDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author ayushi
 */
public class StoreAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form StoreAdminWorkArea
     */
    private JPanel userProcessContainer;
    private Store store;
    private SupplierDirectory supplierDirectory;
    public StoreAdminWorkArea(JPanel userProcessContainer,Store store, SupplierDirectory supplierDirectory) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.store=store;
        this.supplierDirectory= supplierDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageDrugInventoryJButton = new javax.swing.JButton();
        reportJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        manageDrugInventoryJButton.setFont(new java.awt.Font("Calibri", 3, 17)); // NOI18N
        manageDrugInventoryJButton.setForeground(new java.awt.Color(153, 0, 51));
        manageDrugInventoryJButton.setText("Manage Drug Inventory>>");
        manageDrugInventoryJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageDrugInventoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDrugInventoryJButtonActionPerformed(evt);
            }
        });

        reportJButton.setFont(new java.awt.Font("Calibri", 3, 17)); // NOI18N
        reportJButton.setForeground(new java.awt.Color(153, 0, 51));
        reportJButton.setText("Generate The Report>>");
        reportJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reportJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportJButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Calibri", 3, 17)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("<< Back");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(reportJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manageDrugInventoryJButton)))
                .addGap(299, 299, 299))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(manageDrugInventoryJButton)
                .addGap(53, 53, 53)
                .addComponent(reportJButton)
                .addGap(116, 116, 116)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageDrugInventoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDrugInventoryJButtonActionPerformed
        // TODO add your handling code here:
        ManageInventoryCatalog mic = new ManageInventoryCatalog(userProcessContainer, store, supplierDirectory);
        userProcessContainer.add("ManageInventoryCatalog", mic);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageDrugInventoryJButtonActionPerformed

    private void reportJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportJButtonActionPerformed
        // TODO add your handling code here:
        Report r = new Report(userProcessContainer, store, supplierDirectory);
        userProcessContainer.add("ManageInventoryCatalog", r);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_reportJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton manageDrugInventoryJButton;
    private javax.swing.JButton reportJButton;
    // End of variables declaration//GEN-END:variables
}
