/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Drug;
import Business.StoreCatalog;
import Business.Supplier;
import Business.SupplierDirectory;
import UserInterface.CVSAdminRole.AdminAreaWorkPlace;
import UserInterface.StoreAdminRole.LoginStore;
import UserInterface.SupplierRole.LoginSupplier;
import java.awt.CardLayout;

/**
 *
 * @author ayushi
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private SupplierDirectory supplierDirectory;
    private StoreCatalog storeCatalog;
    
    
    public MainJFrame() {
        initComponents();
        supplierDirectory = new SupplierDirectory();
        storeCatalog = new StoreCatalog();
        initialization();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        AdminJButton = new javax.swing.JButton();
        StoreAdminJButton = new javax.swing.JButton();
        SupplierJButton1 = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminJButton.setFont(new java.awt.Font("Calibri", 3, 17)); // NOI18N
        AdminJButton.setForeground(new java.awt.Color(153, 0, 51));
        AdminJButton.setText("CVS Administrator");
        AdminJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminJButtonActionPerformed(evt);
            }
        });

        StoreAdminJButton.setFont(new java.awt.Font("Calibri", 3, 17)); // NOI18N
        StoreAdminJButton.setForeground(new java.awt.Color(153, 0, 51));
        StoreAdminJButton.setText("Store Administrator");
        StoreAdminJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StoreAdminJButtonActionPerformed(evt);
            }
        });

        SupplierJButton1.setFont(new java.awt.Font("Calibri", 3, 17)); // NOI18N
        SupplierJButton1.setForeground(new java.awt.Color(153, 0, 51));
        SupplierJButton1.setText("Supplier");
        SupplierJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StoreAdminJButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(SupplierJButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(AdminJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203)
                .addComponent(StoreAdminJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(221, 221, 221)
                    .addComponent(SupplierJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(333, Short.MAX_VALUE)))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        userProcessContainer.setBackground(new java.awt.Color(255, 255, 255));
        userProcessContainer.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CVS PHARMA INVENTORY");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        userProcessContainer.add(jLabel2, "card2");

        jSplitPane1.setRightComponent(userProcessContainer);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StoreAdminJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StoreAdminJButtonActionPerformed
        // TODO add your handling code here:
    LoginStore lp = new LoginStore(userProcessContainer, supplierDirectory, storeCatalog);
    userProcessContainer.add("LoginStore", lp);
    CardLayout layout = (CardLayout)userProcessContainer.getLayout();
    layout.next(userProcessContainer);
    }//GEN-LAST:event_StoreAdminJButtonActionPerformed

    private void SupplierJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierJButton1ActionPerformed
        // TODO add your handling code here: 
    LoginSupplier ls = new LoginSupplier(userProcessContainer, supplierDirectory);
    userProcessContainer.add("LoginSupplier", ls);
    CardLayout layout = (CardLayout)userProcessContainer.getLayout();
    layout.next(userProcessContainer);
        
    }//GEN-LAST:event_SupplierJButton1ActionPerformed

    private void AdminJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminJButtonActionPerformed
        // TODO add your handling code here:
        AdminAreaWorkPlace panel = new AdminAreaWorkPlace(userProcessContainer, supplierDirectory,storeCatalog);
        userProcessContainer.add("AdminAreaWorkPlace", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_AdminJButtonActionPerformed

    public void initialization(){
     Supplier s1 = supplierDirectory.addSupplier();
     s1.setSupplierName("Supplier1");  
     Supplier s2 = supplierDirectory.addSupplier();
     s2.setSupplierName("Supplier2");  
     Supplier s3 = supplierDirectory.addSupplier();
     s3.setSupplierName("Supplier3");  
     Supplier s4 = supplierDirectory.addSupplier();
     s4.setSupplierName("Supplier4");  
     Supplier s5 = supplierDirectory.addSupplier();
     s5.setSupplierName("Supplier5");  
     
     Drug d1= s1.getDrugCatalog().addDrug();
     d1.setDrugName("Crocin");
     d1.setDrugId(1);
     d1.setPharmaComp("Ranbaxy");
     d1.setComposition("250");
     d1.setConcentration("75");
     d1.setListPrice("200");
     d1.setMfgContact("9876543");
     d1.setMfgEmail("abc@gmail.com");
     d1.setMfglic("A1");
     d1.setMrktBy("Azy");
     d1.setAvail(100);
     Drug d2= s1.getDrugCatalog().addDrug();
     d2.setDrugName("Omex");
     d2.setDrugId(1);
     d2.setPharmaComp("Ranbaxy");
     d2.setComposition("250");
     d2.setConcentration("75");
     d2.setListPrice("200");
     d2.setMfgContact("9876543");
     d2.setMfgEmail("abc@gmail.com");
     d2.setMfglic("A1");
     d2.setMrktBy("Azy");
     d2.setAvail(100);
     Drug d3= s2.getDrugCatalog().addDrug();
     d3.setDrugName("Casper");
     d3.setDrugId(1);
     d3.setPharmaComp("ABPComp");
     d3.setComposition("250");
     d3.setConcentration("75");
     d3.setListPrice("200");
     d3.setMfgContact("9876543");
     d3.setMfgEmail("abc@gmail.com");
     d3.setMfglic("A2");
     d3.setMrktBy("Azy");
     d3.setAvail(100);
     Drug d4= s2.getDrugCatalog().addDrug();
     d4.setDrugName("Paracetamol");
     d4.setDrugId(1);
     d4.setPharmaComp("ABPComp");
     d4.setComposition("250");
     d4.setConcentration("75");
     d4.setListPrice("200");
     d4.setMfgContact("9876543");
     d4.setMfgEmail("abc@gmail.com");
     d4.setMfglic("A2");
     d4.setMrktBy("Azy");
     d4.setAvail(100);
     Drug d5= s3.getDrugCatalog().addDrug();
     d5.setDrugName("Aspirin");
     d5.setDrugId(1);
     d5.setPharmaComp("Cetaphil");
     d5.setComposition("250");
     d5.setConcentration("75");
     d5.setListPrice("200");
     d5.setMfgContact("9876543");
     d5.setMfgEmail("abc@gmail.com");
     d5.setMfglic("A3");
     d5.setMrktBy("Azy");
     d5.setAvail(100);
     
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminJButton;
    private javax.swing.JButton StoreAdminJButton;
    private javax.swing.JButton SupplierJButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
